Infisical/terraform-provider-infisical

README.md, docs/data-sources/secrets.md, docs/index.md, docs/resources/secret.md, examples/data-sources/infisical_secrets/data-source.tf, examples/provider/provider.tf, examples/resources/infisical_secret/resource.tf, infisical/provider/provider.go, infisical/provider/secret_resource.go, infisical/provider/secrets_data_source.go, provider-install-verification/main.tf
Documentation for machine identity auth, and updated examples & README.
=> (Docs): Documentation for machine identity auth

docs/resources/project_role.md, internal/provider/resource/project_role_resource.go
Fixed infinite drift on project role description. Fixed by setting a default value on the description, so it defaults to an empty string, instead of `null`.
=> fix(project-role-resource): infinite drift on project role description

docs/resources/project_identity_specific_privilege.md, docs/resources/project_role.md, internal/provider/resource/project_role_resource.go
Added missing permission subjects to terraform provider. The terraform provider is now inline with our API and [permissions documentation](https://infisical.com/docs/internals/permissions).
=> fix: added missing permission subjects to terraform provider

docs/resources/project_group.md, examples/resources/infisical_project_group/resource.tf
This PR ensures that project group documentation demonstrates using "ID" rather than slug (like in the image below)
=> misc: updated project group documentation to use id

internal/client/project_user.go, internal/provider/resource/project_user_resource.go
This PR resolves a bug, causing TF to error out with "Project membership not found", if the membership has been removed in Infisical. This can happen if the user manually leaves the project, or if they are removed through other means, such as by an admin.
We should always assume the terraform definitions should be the true state of Infisical. So this makes sure that if the project membership isn't found in Infisical, it will be re-created as per defined in Terraform, and then the TF state will be back in sync.
> [!CAUTION]
> This PR is dependent on https://github.com/Infisical/infisical/pull/2480, which should be merged and deployed before this is released.
=> fix(project-user-resource): tf error if membership gets removed in infisical

internal/provider/resource/identity.go, internal/provider/resource/identity_aws_auth.go, internal/provider/resource/identity_azure_auth.go, internal/provider/resource/identity_gcp_auth.go, internal/provider/resource/identity_kubernetes_auth.go, internal/provider/resource/identity_universal_auth.go, internal/provider/resource/identity_universal_auth_client_secret.go
This PR will address issues encountered by users during machine identity configuration when they're using OIDC auth or some other auth that's not universal auth
=> fix: resolved machine identity auth check in old resources

internal/client/model.go, internal/client/project_environment.go, internal/client/secret_folder.go, internal/client/secret_import.go, internal/provider/resource/project_environment.go, internal/provider/resource/project_secret_folder.go, internal/provider/resource/project_secret_import.go
> [!CAUTION]
> This PR depends on https://github.com/Infisical/infisical/pull/2530
This PR introduces Terraform Import support for Project Environments, Secret Imports, and Secrets folders.
The imports are fully ID based, and only take a single ID as input.
**Terraform:**
```terraform
resource "infisical_project_environment" "test-import" {}
```
**Command:**
```bash
terraform import infisical_project_environment.test-import <ENV_ID>
```
**Terraform:**
```terraform
resource "infisical_secret_import" "test-import" {}
```
**Command:**
```bash
terraform import infisical_secret_import.test-import <IMPORT_ID>
```
**Terraform:**
```terraform
resource "infisical_secret_folder" "test-import" {}
```
**Command:**
```bash
terraform import infisical_secret_folder.test-import <FOLDER_ID>
```
=> feat: terraform import support

internal/provider/resource/project_role_resource.go
As the title says, this PR resolves project roles having an infinite drift when no conditions in the permissions are set.
=> fix: project role drift when no conditions are set

docs/resources/identity.md, docs/resources/project_identity.md, examples/resources/infisical_identity/resource.tf, internal/client/model.go, internal/provider/resource/identity.go, internal/provider/resource/project_identity_resource.go
This PR implements a fix for Terraform to properly support identities with multiple auth methods. The `auth_methods` and `auth_modes` variables aren't actually used, but they are preserved in the state. This PR fixes the state to include an array of auth methods, returned by the API.
=> feat: identity multi-auth

internal/client/model.go
This PR fixes a breaking change in 0.12.1
```
CreateIntegrationAuth: Unsuccessful response.
[response={"statusCode":401,"message":[{"validation":"url","code":"invalid_string","message":"Invalid
url","path":["url"]}],"error":"ValidationFailure"}]
```
=> hotfix: integrations url invalid

docs/resources/project_identity_specific_privilege.md, docs/resources/project_role.md, internal/provider/resource/project_identity_specific_privilege.go, internal/provider/resource/project_role_resource.go
This PR updates field type of permissions_v2 field to a list which will enforce the order of elements. In the context of permissions, the order matters a lot
=> misc: update permissions_v2 field to use list instead of set

internal/client/model.go
The `position` parameter was defaulting to 0 when nothing is defined, which is not allowed by our API. I've added `omitempty` to the request field.
=> fix(project-environment): empty position arg defaults to 0

docs/resources/integration_aws_parameter_store.md, docs/resources/integration_aws_secrets_manager.md, examples/resources/infisical_integration_aws_parameter_store/resource.tf, examples/resources/infisical_integration_aws_secrets_manager/resource.tf, internal/client/integrations_auth.go, internal/client/model.go, internal/provider/resource/integration_aws_parameter_store.go, internal/provider/resource/integration_aws_secrets_manager.go, internal/provider/resource/integration_circleci.go, internal/provider/resource/integration_databricks.go, internal/provider/resource/integration_gcp_secret_manager.go
This PR fixes integration not updating when changing from auth fields and integration fields.
Before merging this, [this PR](https://github.com/Infisical/infisical/pull/2855) should be merged
=> fix: resolved update not change the integration auth

docs/resources/project_identity_specific_privilege.md, docs/resources/project_role.md, examples/resources/infisical_project_role/resource.tf, internal/provider/resource/project_identity_specific_privilege.go, internal/provider/resource/project_role_resource.go
This PRs adds an example of using `secretPath` in the conditions object of permissions_v2. This also adds a reference to the documentation for usage of conditions
=> misc: added doc reference for permissions_v2 conditions usgae

internal/pkg/modifiers/comma_space_map_modifier.go, internal/provider/resource/identity_oidc_auth.go
Fixed bug causing Terraform to provide invalid plan error when `bound_claims.repository` was not formatted WITH spaces between comma-separated items.
The OIDC auth resource now supports both with/without spaces between comma-separated items.
=> fix(oidc-auth): comma formatted bound claims required space formatting

internal/client/model.go, internal/provider/resource/integration_aws_parameter_store.go, internal/provider/resource/integration_aws_secrets_manager.go, internal/provider/resource/integration_circleci.go, internal/provider/resource/integration_databricks.go
This ensures that when integrations are updated, it doesn't disable the integration sync entirely.
=> fix: addressed issue where integration is disabled when updated

.github/workflows/test.yml, docs/resources/project_group.md, examples/resources/infisical_project_group/resource.tf, internal/client/model.go, internal/client/project_group.go, internal/provider/resource/project_group.go
This PR introduces support for adding groups to projects by group name instead of just group ID. This is now possible because group names are unique within organizations.
Note, this PR depends on https://github.com/Infisical/infisical/pull/2997.
=> feat(infisical-project-group): link group by name

docs/index.md, internal/provider/provider.go
This PR adds documentation for all supported provider environment variables except service token. I also slightly updated the description for the `client_id` and `client_secret` field, as they are considered legacy, and the `auth` attribute should be used instead.
=> docs: provider environment variables

internal/provider/resource/project_user_resource.go
This PR fixes a provider crash caused by trying to invite a user to a project whom is already invited to the project.
```
│ Error: Error inviting user
│ 
│   with infisical_project_user.test-user,
│   on resource.tf line 20, in resource "infisical_project_user" "test-user":
│   20: resource "infisical_project_user" "test-user" {
│ 
│ Couldn't create project user to Infiscial, no invite was created. Is the user already in the project?
```
```
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Stack trace from the terraform-provider-infisical plugin:
panic: runtime error: index out of range [0] with length 0
goroutine 66 [running]: …
```
=> fix: add length check to project user create

internal/provider/resource/project_group.go
This PR adds URL encoding so that when group name contains escaped characters - it works fine with using the name in endpoitn as url params
=> URL encoding to project group name parameter

docs/resources/project.md, docs/resources/project_user.md, examples/resources/infisical_project/resource.tf, internal/client/model.go, internal/provider/resource/project_resource.go, internal/provider/resource/project_user_resource.go
This PR adds templating support for projects created via. Terraform. It's only supported on the initial create, since there's no way to change the template once a project is created. We use a RequireReplace modifier to insure that the template isn't changed.
Additionally, I added a RequireReplace on the project_user resource's projectId field. We should be replacing memberships if the project ID changes (such as if the project gets replaced)
=> feat(project-resource): template support

docs/resources/identity_oidc_auth.md, internal/client/model.go, internal/provider/resource/identity_oidc_auth.go
This PR adds support for OIDC auth claim metadata mapping, which was recently introduced to OIDC auth.
=> feat(oidc-auth): claim metadata mapping

.github/workflows/release-crossplane.yml
This addresses the following build error
=> misc: added missing terraform setup step in crossplane release

.github/workflows/release-crossplane.yml
This PR ensures that crossplane release works even when some changes are not present in git (because we force the files)
=> misc: add skip validate for crossplane release

internal/client/model.go
Users reported secret change approval policy user changes are not getting updated. 
I was able to reproduce this and it seems this was broken long time back. The Go JSON key type is called name where as API expected it to be `username`
=> feat: corrected issue of secret change policy approvers not working

internal/client/model.go, internal/provider/resource/secret_resource.go
This PR adds support for importing a secret using the `<workspace>:<env>:<secret-path>:<secret-name>` format. 
While making sure that users can still import a secret using the Secret UUID.
=> feat: support semantic id format in secret import (ENG-3588)
